[platformio]
default_envs = minima_counter
build_dir = ../../build/can-bench-minima
core_dir = ../../build/can-bench-pio

[env:minima_counter]
platform = renesas-ra@1.9.0
board = uno_r4_minima
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra
